server:
  port: 9000
spring:
  main:
    allow-bean-definition-overriding : true
  datasource:
    url: jdbc:postgresql://localhost:5432/milky-way
    username: postgres
    password: milkyway
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
        hibernate:
            jdbc:
                lob:
                  non_contextual_creation: true
